---
tags: [go-sdk]
---
:toc:
:icons: font
:source-highlighter: prettify
:project_id: go-sdk

This guide explains how to use http://developer.couchbase.com/documentation/server/current/sdk/go/start-using-sdk.html[Couchbase Go SDK] to store and retrieve a JSON document in http://developer.couchbase.com/server[Couchbase].

== What you'll build

Couchbase is an open source NoSQL document database. It can be programmed using a variety of languages. This guide will show how to write a simple Go application to store a JSON document representing a Book JSON document in Couchbase Server using the Couchbase Go SDK.

== What you'll need

* 15-30 minutes
* A Go code editor
* http://www.couchbase.com/nosql-databases/downloads[Couchbase Server 4.5+]

== Setup

=== Install and Start Couchbase

Install and start Couchbase for your operating system as explained at: http://developer.couchbase.com/documentation/server/current/getting-started/installing.html. A default bucket by the name `default` is created for you.

Open up Couchbase Web Console at http://localhost:8091, go the Query tab, create a primary index using `CREATE PRIMARY INDEX on default` and click on Execute button to create the index.

=== Install Go Client SDK

Couchbase Go Client SDK can be installed on different operating systems. Complete set of instructions are available at http://developer.couchbase.com/documentation/server/current/sdk/go/start-using-sdk.html. OSX specific instructions are given below.

Go Client SDK on OSX requires to install Go language programming language distribution. This in turn requires to install XCode and the process could take a few minutes depending upon your connectivity. 

. Download and Install https://itunes.apple.com/au/app/xcode/id497799835?mt=12[XCode].
. Install the XCode CLI tools as `xcode-select --install`.
. Download https://golang.org/dl/[Go package installer], open it and follow the prompts to install it. The package installs the Go distribution to `/usr/local/go` directory.
+
The installer adds `/usr/local/go/bin` directory in your `PATH` environment variable. You may need to restart any open Terminal sessions for the change to take effect.
+
. Now you are ready to install Couchbase Go SDK:
+

```
go get gopkg.in/couchbase/gocb.v1
```
+
This will first install the `libcouchbase` library, then Python interpreter, and finally the Couchbase Python library.

== Code

== Create Application

In your favorite editor, create a new file `app.go`. Copy the following code in that file:

[source,go]
----
package main

import (
	"fmt"
	"gopkg.in/couchbase/gocb.v1"
)

type Book struct {
	ISBN string `json:"isbn"`
	Name string `json:"name"`
	Cost string `json:"cost"`
}

func main() {
	cluster, _ := gocb.Connect("couchbase://localhost")
	bucket, _ := cluster.OpenBucket("default", "")

	bucket.Upsert("u:book1",
		Book{
			isbn: "978-1-4919-1889-0",
			name: "Minecraft Modding with Forge",
			cost: "29.99",
		}, 0)

	// Get the value back
	var inBook Book
	bucket.Get("u:book1", &inBook)
	fmt.Printf("Book: %v\n", inBook)

	// Use query
	query := gocb.NewN1qlQuery("SELECT * FROM default")
	rows, err := bucket.ExecuteN1qlQuery(query, nil)
	if (err != nil) {
		fmt.Printf(err.Error())
		return;
	}
	var row interface{}
	for rows.Next(&row) {
		fmt.Printf("Row: %v", row)
	}
}
----

Couchbase Go library is used in this class.

A new Go struct named `Book` is defined that mimics the JSON docuemnt structure. `Connect` method a connection to the Couchbase node identified by `localhost`. The `default` bucket is opened using the `OpenBucket` method.

A JSON document is upserted in the bucket. The word `"Upsert"` comes from `"update"` and `"insert"`. So this method will either insert the document if it does not exist, or update if it already exists. A fresh install of Couchbase has an empty `default` bucket. So the document will be inserted for the first run. Subsequent runs of this application will update the document.

A key is given to identify the document, this is `book1` in our case. The document itself is the JSON fragment and is the second parameter of the method.

The inserted document can be easily accessed using `bucket.Get()` method and passing the key used during the creation. Value of the document can be retrieved using `.value`.

All documents from the bucket can be easily retrieved using http://couchbase.com/n1ql[N1QL] query as well.

== Run

=== Build Application

Open a terminal or command prompt and give the following command to build the application:

```
go buid app.go
```

This will compile the source code and generate the binary file.

=== Run Application

In the same directory, run the application by giving the command:

```
app
```

It will show the output as:

[source, text]
----
Book: {978-1-4919-1889-0 Minecraft Modding with Forge 29.99}
Row: map[default:map[name:Minecraft Modding with Forge cost:29.99 isbn:978-1-4919-1889-0]]
----

The first result comes from `bucket.Get("u:book1", &inBook)` method. The second line comes from executing the N1QL query and iterating over all the documents.

== Summary

Congratulations! You set up a Couchbase server and wrote a simple Go application that stores and retrieves a JSON document in Couchbase.

